name: MAIN

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_docker_images:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - shell: cmd
      name: Build the Docker image
      env:
        POLIGON_API: ${{ secrets.POLIGON_API }}
        LUNCHMONEY_API: ${{ secrets.LUNCHMONEY_API }}
      run: docker build . --file Dockerfile --build-arg POLIGON_API="$POLIGON_API" --build-arg LUNCHMONEY_API="$LUNCHMONEY_API"
